news/urls.py
from django.urls import path 
from .views import home, articoloDetailView, index, listaArticoli, queryBase

app_name='news'

urlpatterns=[
    path('', home, name='homeview'),
    path('index', index, name='index'),
    path("articolo/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("query", queryBase, name="query"),



]   

prima_app/urls.py
from django.urls import path
from prima_app.views import homepage, welcome, lista, chi_siamo, variabili, index

app_name="prima_app"
urlpatterns=[
    path('', index, name='index'),
    path('homepage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chi_siamo', chi_siamo, name='chi_siamo'),
    path('variabili', variabili, name='variabili'),

]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_root

urlpatterns = [
    path('', index_root, name='index_root'),
    path('admin/', admin.site.urls),
    path('prima_app', include("prima_app.urls", namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_1/', include("prova_pratica_1.urls", namespace="prova_pratica_1")),
    path('news/', include("news.urls", namespace="news")),
]

prima_app/views.py
from django.shortcuts import render

# Create your views here.
def homepage(request):
    return render(request, "prima_app/homepage.html")

def welcome(request):
    return render(request, "prima_app/welcome.html")
    
def lista(request):
    return render(request, "prima_app/lista.html")

def chi_siamo(request):
    return render(request, "prima_app/chi_siamo.html")

def variabili(request):
    context={
        'var1':'Prima variabile',
        'var2':'Seconda variabile',
        'var3':'Terza variabile',
    }
    return render(request, "variabili.html", context)

def index(request):
    return render(request, "prima_app/index.html")

prima_app/templates/prima_app/chi_siamo.html
{% extends "base.html" %}
{%block title%}{{block.super}} | Chi Siamo{%endblock title%}
{%block content%}
<p>Chi Siamo</p>
<h2>ChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamo<br>ChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamo<br>ChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamoChiSiamo
</h2>
{%endblock content%}

prima_app/templates/prima_app/homepage.html
{% extends "base.html" %}

{%block title%}{{block.super}} | HomePage{%endblock title%}
{% block content %}
<h1>Benvenuto</h1>
{% endblock content %}

prima_app/templates/prima_app/index.html
{% extends "base.html" %}
{%block title%}{{block.super}} | Index{%endblock title%}
{%block content%}
    <ol>
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
        <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
        <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
    </ol>
{%endblock content%}

prima_app/templates/prima_app/lista.html
{% extends "base.html" %}
{%block title%}{{block.super}} | Lista{%endblock title%}
{%block content%}
<body>
    <p>The Listone</p>
    <ol>
        <li>Primero</li>
        <li>Segundo</li>
        <li>Tercero</li>
    </ol>
</body>
{%endblock content%}

prima_app/templates/prima_app/variabili.html
{% extends "base.html" %}
{%block title%}{{block.super}} | Variabili{%endblock title%}
{%block content%}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{%endblock content%}

prima_app/templates/prima_app/welcome.html
{% extends "base.html" %}
{%block title%}{{block.super}} | Welcome{%endblock title%}
{%block content%}
<p>Welcome</p>
    <h2>WelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcome<br>WelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcome<br>WelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcomeWelcome</h2>
</body>
{%endblock content%}