news/urls.py
from django.urls import path 
from .views import home, articoloDetailView, index, listaArticoli, queryBase

app_name='news'

urlpatterns=[
    path('', home, name='homeview'),
    path('index', index, name='index'),
    path("articolo/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli", listaArticoli, name="lista_articoli"),
    path("lista_articoli/<int:pk>", listaArticoli, name="lista_articoli"),
    path("query", queryBase, name="query"),



]   

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_root

urlpatterns = [
    path('', index_root, name='index_root'),
    path('admin/', admin.site.urls),
    path('prima_app', include("prima_app.urls", namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_1/', include("prova_pratica_1.urls", namespace="prova_pratica_1")),
    path('news/', include("news.urls", namespace="news")),
]

news/models.py
from django.db import models

class Giornalista(models.Model):
    nome=models.CharField(max_length=20)
    cognome=models.CharField(max_length=20)
    anno_di_nascita=models.DateField(blank=True)

    def __str__(self):
        return self.nome +" "+self.cognome

    class Meta:
        verbose_name="Giornalista"
        verbose_name_plural="Giornalisti"


class Articolo(models.Model):
    titolo=models.CharField(max_length=100)
    contenuto=models.TextField()
    giornalista=models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")
    data=models.DateField(blank=True)
    visualizzazioni=models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name="Articolo"
        verbose_name_plural="Articoli"



# Create your models here.

news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Articolo, Giornalista   
import datetime
# Create your views here.

def home(request):
    articoli = Articolo.objects.all()
    giornalisti = Giornalista.objects.all()
    context = {"articoli": articoli, "giornalisti" : giornalisti}
    print(context)
    return render(request, "news/homepage.html", context)

def index(request):
    return render(request, "news/index.html")

def articoloDetailView(request, pk):
    articolo=get_object_or_404(Articolo, pk=pk)
    context={"articolo":articolo}
    return render(request, "lista_articoli.html", context)

def listaArticoli(request, pk=None):
    if(pk==None):
        articoli = Articolo.objects.all()
        giornalista=None
    else:
        articoli=Articolo.objects.filter(giornalista_id=pk)
        giornalista=Giornalista.objects.get(pk=pk)
    if(pk==None):
        is_giornalista=False
    else:
        is_giornalista=True
    context={
        'articoli':articoli,
        'is_giornalista':is_giornalista,
        'giornalista':giornalista
    }
    return render(request, 'lista_articoli.html', context)

def queryBase(request):
    #tutti gli articoli scritti da giornalisti di un certo cognome 
    articoli_cognome=Articolo.objects.filter(giornalista__cognome="Colombo")
    #totale 
    numero_totale_articoli = Articolo.objects.count()

    #contare numero articoli scritti da un giornalista specifico
    giornalista_1=Giornalista.objects.get(id=1)
    numero_articoli_giornalista_1=Articolo.objects.filter(giornalista=giornalista_1).count()

    #ordinare gli articoli per numero di visualizzazioni in ordine decrescente
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni')

    #tutti gli articoli che non hanno visualizzazioni
    articoli_senza_visualizzazioni=Articolo.objects.filter(visualizzazioni=0)

    #articolo più visualizzato
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()

    #tutti i giornalisti nati dopo una certa data
    giornalisti_data=Giornalista.objects.filter(anno_di_nascita__gt=datetime.date(1990,1,1))

    #tutti gli articoli pubblicati in una data specifica
    articoli_del_giorno = Articolo.objects.filter(data=datetime.date(2023,1,1))

    #tutti gli articoli pubblicati in un intervallo di date
    articoli_periodo=Articolo.objects.filter(data__range=(datetime.date(2023,1,1), datetime.date(2023,12,31)))

    #gli articoli scritti da giornalisti nati prima del 1980
    giornalisti_nati=Giornalista.objects.filter(anno_di_nascita__lt=datetime.date(1980,1,1))
    articoli_giornalisti=Articolo.objects.filter(giornalista__in=giornalisti_nati)

    #il giornalista + giovane
    giornalista_giovane=Giornalista.objects.order_by('-anno_di_nascita').first()

    #il giornalista + vecchio
    giornalista_vecchio=Giornalista.objects.order_by('anno_di_nascita').first()

    #gli ultimi 5 articoli pubblicati
    ultimi=Articolo.objects.order_by('-data')[:5]

    #tutti gli articoli con un certo numero minimo di visualizzazioni
    articoli_minime_visualizzazioni=Articolo.objects.filter(visualizzazioni__gte=100)

    #tutti gli articoli che contengono una certa parola nel titolo
    articoli_parola=Articolo.objects.filter(titolo__icontains='articolo')

    #Articoli pubblicati in nun certo mese di un anno spcifico
    articoli_mese_anno=Articolo.objects.filter(data__month=1,data__year=2023)

    #Giornalisti con almeno un articolo con più di 100 visualizzazioni
    giornalisti_con_articoli_popolari=Giornalista.objects.filter(articoli__visualizzazioni__gt=100).distinct()

    data=datetime.date(1990,1,1)
    visualizzioni=50

    #scrivi quali articoli vengono selezionati
    articoli_con_and=Articolo.objects.filter(giornalista__anno_di_nascita__gt=data, visualizzazioni__gte=visualizzioni)

    #per mettere in or le condizioni utilizzare Q
    from django.db.models import Q
    #scrivi quali articoli vengono selezionati
    articoli_con_or=Articolo.objects.filter(Q(giornalista__anno_di_nascita__gt=data) | Q(visualizzazioni__lte=visualizzioni))

    #per il not utilizzare Q
    #scrivi quali articoli vengono selezionati
    articoli_con_not=Articolo.objects.filter(~Q(giornalista__anno_di_nascita__gt=data))
    #oppure con il metodo exclude
    articoli_con_not=Articolo.objects.exclude(giornalista__anno_di_nascita__lt=data)

    context={
        'articoli_cognome':articoli_cognome,
        'numero_totale_articoli':numero_totale_articoli,
        'numero_articoli_giornalista_1':numero_articoli_giornalista_1,
        'articoli_ordinati': articoli_ordinati,
        'articoli_senza_visualizzazioni':articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato':articolo_piu_visualizzato,
        'giornalisti_data':giornalisti_data,
        'articoli_del_giorno':articoli_del_giorno,
        'articoli_periodo':articoli_periodo,
        'articoli_giornalisti':articoli_giornalisti,
        'giornalista_giovane':giornalista_giovane,
        'giornalista_vecchio':giornalista_vecchio,
        'ultimi':ultimi,
        'articoli_minime_visualizzazioni':articoli_minime_visualizzazioni,
        'articoli_parola':articoli_parola,
        'articoli_mese_anno':articoli_mese_anno,
        'giornalisti_con_articoli_popolari':giornalisti_con_articoli_popolari,
        'articoli_con_and':articoli_con_and,
        'articoli_con_or':articoli_con_or,
        'articoli_con_not':articoli_con_not,
    }

    return render(request, "query.html" ,context)

news/templates/news/articolo_detail.html
{% extends 'base.html' %}
{% block title%}
    {{articolo.titolo}}
{% endblock title %}

{% block content %}
    <h1>{{articolo.titolo}}</h1>
    <h3>{{articolo.contenuto}}</h3>
    <h5>Autore: {{articolo.giornalista}}</h5>
{% endblock content%}

news/templates/news/homepage.html
{% extends "base.html" %}
{% block title %}
    Articoli e Giornalisti
{% endblock title %}
{% block content %}
    <h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Titolo:</strong> {{ articolo.titolo }}</p>
        <p><strong>Contenuto:</strong> {{ articolo.contenuto }}</p>
        <p><strong>Autore:</strong> {{ articolo.giornalista }}</p>
        <hr>
    {% endfor %}
    <h4>Giornalisti:</h4>
    {% for giornalista in giornalisti %}
        <p><strong>Nome:</strong> {{ giornalista.nome }}</p>
        <p><strong>Cognome:</strong> {{ giornalista.cognome }}</p>
        <hr>
    {% endfor %}
{% endblock content %}

news/templates/news/index.html
{% extends 'base.html' %}

{% block title %}Index News{% endblock title %}</title>
    {%block content%}
    <ol>
        <li><a href="{% url 'news:homeview'%}">Homepage</a></li>
        <li><a href="{% url 'news:lista_articoli' 1%}">Articolo Detail</a></li>
    </ol>
{%endblock content%}

news/templates/news/lista_articoli.html
{% extends 'base.html' %}
{% block title %}
  Lista
{% endblock %}

{% block content %}
  {% if is_giornalista %}
    <h1>Lista Articolo di {{ giornalista.nome }} {{ giornalista.cognome }}:</h1>
    {% for articolo in articoli %}
      <h3>{{ articolo.titolo }}</h3>
      <p>{{ articolo.contenuto }}</p>
      <hr>
    {% endfor %}
  {% else %}
    <h1>Lista Articoli</h1>
    {% for articolo in articoli %}
      <h3>{{ articolo.titolo }}</h3>
      <p>{{ articolo.contenuto }}</p>
      <p>Autore: {{ articolo.giornalista }}</p>
      <hr>
    {% endfor %}
  {% endif %}
{% endblock %}

news/templates/news/query.html
{% extends 'base.html' %}

{% block title %}
  Query Base
{% endblock %}
{% block content %}
  <h2>1. Articoli scritti da Colombo:</h2>
  <ul>
    {% for articolo in articoli_cognome %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.contenuto }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>2. Numero totale di articoli:</h2>
  <ul>
    <li>{{ numero_totale_articoli }}</li>
    <hr />
  </ul>
  <h2>3. Numero totale di articoli del Giornalista 1:</h2>
  <ul>
    <li>{{ numero_articoli_giornalista_1 }}</li>
    <hr />
  </ul>
  <h2>4. Articoli in ordine decrescente di visualizzazioni:</h2>
  <ol>
    {% for articolo in articoli_ordinati %}
      <li>{{ articolo.titolo }}</li>
      <ul>
        <li>{{ articolo.giornalista.nome }}</li>
        <li>{{ articolo.giornalista.cognome }}</li>
        <li>{{ articolo.contenuto }}</li>
        <li>{{ articolo.visualizzazioni }}</li>
      </ul>
      <hr />
    {% endfor %}
  </ol>
  <h2>5. Tutti gli articoli senza visualizzazioni</h2>
  <ul>
    {% for articolo in articoli_senza_visualizzazioni %}
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>6. Articolo più visualizzato:</h2>
  <ul>
    <li>{{ articolo_piu_visualizzato.giornalista.nome }}</li>
    <li>{{ articolo_piu_visualizzato.giornalista.cognome }}</li>
    <li>{{ articolo_piu_visualizzato.contenuto }}</li>
    <li>{{ articolo_piu_visualizzato.visualizzazioni }}</li>
    <hr />
  </ul>
  <h2>7. Tutti i giornalisti nati dopo 01/01/1990:</h2>
  <ul>
    {% for giornalista in giornalisti_data %}
      <li>{{ giornalista.nome }}</li>
      <li>{{ giornalista.cognome }}</li>
      <li>{{ giornalista.anno_di_nascita }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>8. Tutti gli articoli pubblicati il 01/01/2023:</h2>
  <ul>
    {% for articolo in articoli_del_giorno %}
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <li>{{ articolo.data }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>9. Tutti gli articoli pubblicati tra il 01/01/2023 e il 31/12/2023:</h2>
  <ul>
    {% for articolo in articoli_periodo %}
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <li>{{ articolo.data }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>10. Articoli scritti da giornalisti nati prima del 1980:</h2>
  <ul>
    {% for articolo in articoli_giornalisti %}
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.giornalista.anno_di_nascita }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>11. Giornalista più giovane:</h2>
  <ul>
    <li>{{ giornalista_giovane }}</li>
    <li>{{ giornalista_giovane.anno_di_nascita }}</li>
    <hr />
  </ul>
  <h2>12. Giornalista più anziano:</h2>
  <ul>
    <li>{{ giornalista_vecchio }}</li>
    <li>{{ giornalista_vecchio.anno_di_nascita }}</li>
    <hr />
  </ul>
  <h2>13. Ultimi 5 articoli pubblicati:</h2>
  <ol>
    {% for articolo in ultimi %}
      <li>{{ articolo.titolo }}</li>
      <ul>
        <li>{{ articolo.giornalista.nome }}</li>
        <li>{{ articolo.giornalista.cognome }}</li>
        <li>{{ articolo.contenuto }}</li>
        <li>{{ articolo.visualizzazioni }}</li>
        <li>{{ articolo.data }}</li>
        <hr />
      </ul>
    {% endfor %}
  </ol>
  <h2>14. Tutti gli articoli con almeno 100 visualizzazioni:</h2>
  <ul>
    {% for articolo in articoli_minime_visualizzazioni %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <li>{{ articolo.data }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>15. Tutti gli articoli che contengono la parola "articolo" nel titolo:</h2>
  <ul>
    {% for articolo in articoli_parola %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <li>{{ articolo.data }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>16. Articoli pubblicati a gennaio 2023:</h2>
  <ul>
    {% for articolo in articoli_mese_anno %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <li>{{ articolo.data }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>17. Giornalisti con almeno 1 articolo con più di 100 visualizzazioni:</h2>
  <ul>
    {% for giornalista in giornalisti_con_articoli_popolari %}
      <li>{{ giornalista.nome }}</li>
      <li>{{ giornalista.cognome }}</li>
      <li>{{ giornalista.anno_di_nascita }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>18. Articoli di giornalisti nati il 01/01/1990 con 50 visualizzazioni</h2>
  <ul>
    {% for articolo in articoli_con_and %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <li>{{ articolo.data }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>19. Articoli di giornalisti nati il 01/01/1990 o con 50 visualizzazioni</h2>
  <ul>
    {% for articolo in articoli_con_or %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.giornalista.anno_di_nascita }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <hr />
    {% endfor %}
  </ul>
  <h2>20. Articoli con giornalisti non nati il 01/01/1990: </h2>
  <ul>
    {% for articolo in articoli_con_not %}
      <li>{{ articolo.titolo }}</li>
      <li>{{ articolo.giornalista.nome }}</li>
      <li>{{ articolo.giornalista.cognome }}</li>
      <li>{{ articolo.giornalista.anno_di_nascita }}</li>
      <li>{{ articolo.contenuto }}</li>
      <li>{{ articolo.visualizzazioni }}</li>
      <hr />
    {% endfor %}
  </ul>
{% endblock %}